apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2Gi  # 수정: 필요한 저장 용량으로 변경
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/d/code/finalproject/database"  # 수정: 호스트 시스템의 실제 경로로 변경